const express = require('express');
const router = express.Router();
const Member = require('../models/Member');
const { Income } = require('../models/Finance');
const { calculateExpiryDate, determinePaymentStatus } = require('../utils/memberUtils');

// Get all members
router.get('/', async (req, res) => {
    try {
        const members = await Member.find().sort({ createdAt: -1 });
        res.json(members);
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
});

// Get member by ID
router.get('/:id', async (req, res) => {
    try {
        const member = await Member.findById(req.params.id);
        if (!member) {
            return res.status(404).json({ error: 'Member not found' });
        }
        res.json(member);
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
});

// Get member by memberCode
router.get('/code/:memberCode', async (req, res) => {
    try {
        const member = await Member.findOne({ memberCode: req.params.memberCode });
        if (!member) {
            return res.status(404).json({ error: 'Member not found' });
        }
        res.json(member);
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
});

// Add new member
router.post('/', async (req, res) => {
    try {
        const {
            memberCode,
            name,
            phone,
            email,
            membershipPlan,
            planAmount,
            paidAmount,
            paymentMethod,
            address,
            emergencyContact
        } = req.body;

        // Calculate expiry date using utility function
        const joinDate = new Date();
        const expiryDate = calculateExpiryDate(membershipPlan, joinDate);

        // Determine payment status using utility function
        const paymentStatus = determinePaymentStatus(paidAmount, planAmount);

        const newMember = new Member({
            memberCode,
            name,
            phone,
            email,
            membershipPlan,
            planAmount,
            paidAmount,
            paymentMethod,
            paymentStatus,
            joinDate,
            expiryDate,
            address,
            emergencyContact
        });

        const savedMember = await newMember.save();
        
        // Automatically create income record for member payment
        try {
            const incomeRecord = new Income({
                title: `Membership Fee - ${name}`,
                amount: paidAmount,
                category: 'Membership Fees',
                description: `Auto-generated income from member ${memberCode} (${membershipPlan})`,
                paymentMethod: paymentMethod,
                date: joinDate,
                isAutoGenerated: true,
                memberId: savedMember._id,
                memberCode: memberCode
            });
            
            await incomeRecord.save();
            console.log(`✅ Auto-generated income record for member ${memberCode}: ₹${paidAmount}`);
        } catch (incomeError) {
            console.error('❌ Failed to create income record:', incomeError);
            // Don't fail the member creation if income recording fails
        }
        
        res.status(201).json(savedMember);
    } catch (error) {
        if (error.code === 11000) {
            res.status(400).json({ error: 'Member code already exists' });
        } else {
            res.status(400).json({ error: error.message });
        }
    }
});

// Update member by ID
router.put('/:id', async (req, res) => {
    try {
        // If membership plan or amounts changed, recalculate payment status
        if (req.body.planAmount && req.body.paidAmount) {
            req.body.paymentStatus = determinePaymentStatus(req.body.paidAmount, req.body.planAmount);
        }

        const updatedMember = await Member.findByIdAndUpdate(
            req.params.id,
            req.body,
            { new: true, runValidators: true }
        );
        if (!updatedMember) {
            return res.status(404).json({ error: 'Member not found' });
        }
        res.json(updatedMember);
    } catch (error) {
        res.status(400).json({ error: error.message });
    }
});

// Update member by memberCode
router.put('/code/:memberCode', async (req, res) => {
    try {
        // If membership plan or amounts changed, recalculate payment status
        if (req.body.planAmount && req.body.paidAmount) {
            req.body.paymentStatus = determinePaymentStatus(req.body.paidAmount, req.body.planAmount);
        }

        const updatedMember = await Member.findOneAndUpdate(
            { memberCode: req.params.memberCode },
            req.body,
            { new: true, runValidators: true }
        );
        if (!updatedMember) {
            return res.status(404).json({ error: 'Member not found' });
        }
        res.json(updatedMember);
    } catch (error) {
        res.status(400).json({ error: error.message });
    }
});

// Delete member by ID
router.delete('/:id', async (req, res) => {
    try {
        const deletedMember = await Member.findByIdAndDelete(req.params.id);
        if (!deletedMember) {
            return res.status(404).json({ error: 'Member not found' });
        }
        res.json({ message: 'Member deleted successfully' });
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
});

// Delete member by memberCode
router.delete('/code/:memberCode', async (req, res) => {
    try {
        const deletedMember = await Member.findOneAndDelete({ memberCode: req.params.memberCode });
        if (!deletedMember) {
            return res.status(404).json({ error: 'Member not found' });
        }
        res.json({ message: 'Member deleted successfully' });
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
});

module.exports = router;