const mongoose = require('mongoose');

// Income Schema
const incomeSchema = new mongoose.Schema({
    title: {
        type: String,
        required: true
    },
    amount: {
        type: Number,
        required: true,
        min: 0
    },
    category: {
        type: String,
        required: true,
        enum: [
            'Membership Fees',
            'Personal Training',
            'Equipment Rental',
            'Supplements Sales',
            'Merchandise',
            'Events/Classes',
            'Other'
        ]
    },
    description: {
        type: String,
        default: ''
    },
    paymentMethod: {
        type: String,
        required: true,
        enum: ['Cash', 'Bank Transfer', 'UPI', 'Credit Card', 'Debit Card', 'Mixed'],
        default: 'Cash'
    },
    date: {
        type: Date,
        default: Date.now
    },
    isAutoGenerated: {
        type: Boolean,
        default: false
    },
    memberId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Member',
        required: false // Only for auto-generated income from member payments
    },
    memberCode: {
        type: String,
        required: false // Only for auto-generated income
    }
}, {
    timestamps: true
});

// Expense Schema
const expenseSchema = new mongoose.Schema({
    title: {
        type: String,
        required: true
    },
    amount: {
        type: Number,
        required: true,
        min: 0
    },
    category: {
        type: String,
        required: true,
        enum: [
            'Equipment Purchase',
            'Maintenance & Repair',
            'Utilities (Electricity, Water)',
            'Rent/Mortgage',
            'Staff Salaries',
            'Insurance',
            'Marketing',
            'Supplies',
            'Cleaning',
            'Other'
        ]
    },
    description: {
        type: String,
        default: ''
    },
    paymentMethod: {
        type: String,
        required: true,
        enum: ['Cash', 'Bank Transfer', 'UPI', 'Credit Card', 'Debit Card'],
        default: 'Cash'
    },
    date: {
        type: Date,
        default: Date.now
    }
}, {
    timestamps: true
});

// Create indexes for better query performance
incomeSchema.index({ date: -1 });
incomeSchema.index({ category: 1 });
incomeSchema.index({ isAutoGenerated: 1 });
incomeSchema.index({ memberCode: 1 });

expenseSchema.index({ date: -1 });
expenseSchema.index({ category: 1 });

const Income = mongoose.model('Income', incomeSchema);
const Expense = mongoose.model('Expense', expenseSchema);

module.exports = { Income, Expense };